export const data = [
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"000.000.000",
                        Impresiones:"000.000",
                        Post_Engagements:"000.000",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"000.000.000",
                        Alcance_Organico:"000",
                        Views_video:"000",
                        Post_Engagements:"000.000",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"000",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
    {
        Nombre:"",
        Apellido:"",
        Redes:[
            {
                insta:[
                    {
                        Seguidores:"",
                        Impresiones:"",
                        Post_Engagements:"",
                    }
                ],
                facebook:[
                    {
                        Seguidores:"",
                        Alcance_Organico:"",
                        Views_video:"",
                        Post_Engagements:"",
                    }
                ],
                twitter:[
                    {
                        Impresiones:"",
                    }
                ]
            }
        ]
    },
]