export const data = [
   {
      Image:"/assets/img/Irma/Irma01.png",
   },
   {
      Image:"/assets/img/Irma/Irma02.png",
   },
   {
      Image:"/assets/img/Irma/Irma03.png",
   },
   {
      Image:"/assets/img/Irma/Irma04.png",
   },
   {
      Image:"/assets/img/Irma/Irma05.png",
   },
   {
      Image:"/assets/img/Irma/Irma06.png",
   },
]