export const data = [
   {
      Nombre:"Andrea",
      Apellido:"Serna",
      Icon:"/assets/icons/Famosos/Andrea_Serna.png",
      Profesion:"Presentadora, influencer, modelo campañas",
      Exp:"Head and Shoulders, Cetaphil, Tous, Avon, Pat Primo, Samsung, Rappi",
      Texto:"Andrea es una gran profesional que ha tenido mucho éxito y reconocimientos a lo largo de su carrera, es una persona muy comprometida con su entrega  en el trabajo. Con Andrea hemos logrado hacer un gran equipo y hemos podido realizar todos nuestros proyectos, tanto nacionales como internacionales.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Serna01.png",
         "/assets/img/Famosos/A_Serna02.png",
      ]
   },
   {
      Nombre:"Adriana",
      Apellido:"Arboleda",
      Icon:"/assets/icons/Famosos/A_Arboleda_Icon.png",
      Profesion:"Diseñadora de modas, presentadora, empresaria, modelo de campañas.",
      Exp:"Pink Filosofy, vocera  del movimento 'Vístete de Colombia'.",
      Texto:"Con su trabajo, que he acompañado durante toda su carrera como modelo, presentador y diseñador, Adriana es una persona que ha creado una marca con estilo, glamour y elegancia. Gracias a su larga trayectoria, es recordada y querida por todos los colombianos.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Arboleda01.png",
         "/assets/img/Famosos/A_Arboleda02.png",
      ]
   },
   {
      Nombre:"Adriana",
      Apellido:"Tarud",
      Icon:"/assets/icons/Famosos/A_Tarud_Icon.png",
      Profesion:"Ex señorita colombia ( ), PR,modelo y presentadora de eventos. ",
      Exp:"",
      Texto:"Adriana se ha posicionado en el medio como una de las mejores relacionistas públicas  del país. Su carísima siempre la ha caracterizado para destacarse en todos sus trabajos.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Tarud01.png",
         "/assets/img/Famosos/A_Tarud02.png",
      ]
   },
   {
      Nombre:"Ana",
      Apellido:"Beliza",
      Icon:"/assets/icons/Famosos/A_Beliza_Icon.png",
      Profesion:"Modelo, influencer, editora de moda @revistalternativa.",
      Exp:"",
      Texto:"Ana es una de las editoras de moda y modelos más jóvenes y preparadas del país. Su carrera siempre ha estado rodeada en el mundo de la moda, se ha destacado notoriamente en las mejores pasarelas de Colombia y por su exitoso blog de moda.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Beliza01.png",
         "/assets/img/Famosos/A_Beliza02.png",
      ]
   },
   {
      Nombre:"Ana Sofía",
      Apellido:"Henao",
      Icon:"/assets/icons/Famosos/A_Henao_Icon.png",
      Profesion:"Modelo, influencer. ",
      Exp:"Aquarella, Kalley , Baby Ganics , Rappi.",
      Texto:"Es una  de las celebridades más recordadas y queridas por los colombianos, desde los inicios  de su trabajo siendo adolecente. Su profesionalismo la ha hecho destacar en diferentes proyectos. Ahora como influencer y escritora de libros para niños ha logrado un reconocimiento especial en el medio. Ana es una persona cariñosa y comprometida.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Henao01.png",
         "/assets/img/Famosos/A_Henao02.png",
      ]
   },
   {
      Nombre:"Alejandra",
      Apellido:"Azcárate",
      Icon:"/assets/icons/Famosos/A_Azcarate_Icon.png",
      Profesion:"Comediante, modelo, presentadora, locutora. ",
      Exp:"Studio F, Aviatur, Blind, Jaguar,Ishop, Apple, Bulova.",
      Texto:"Alejandra es toda una celebridad, un personaje que ha logrado trascender desde sus comienzos como modelo, actriz y presentadora. Con sus shows de stand up comedy demuestra que es una persona con un gran carácter y brillante humor, creatividad y directa al decir las cosas.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Azcarate01.png",
         "/assets/img/Famosos/A_Azcarate02.png",
      ]
   },
   {
      Nombre:"Alexandra",
      Apellido:"Santos",
      Icon:"/assets/icons/Famosos/A_Santos_Icon.png",
      Profesion:"Presentadora, modelo, Health Coach.",
      Exp:"",
      Texto:"Es una persona que ha aprovechado el medio de las comunicaciones para realizarse profesionalmente y ha avanzando en el camino desde el modelaje, la presentación y ahora como health coach y una de sus grandes pasiones la práctica del Yoga.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Santos01.png",
         "/assets/img/Famosos/A_Santos02.png",
      ]
   },
   {
      Nombre:"Ángela",
      Apellido:"Cardozo",
      Icon:"/assets/icons/Famosos/A_Cardozo_Icon.png",
      Profesion:"Presentadora TV, modelo, influencer.",
      Exp:"",
      Texto:"A Ángela la he acompañado desde sus inicios en el modelaje y luego como presentadora de magazines. Con un buen manejo ante las cámaras, es una comunicadora que proyecta credibilidad y empatía.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/A_Cardozo01.png",
         "/assets/img/Famosos/A_Cardozo02.png",
      ]
   },
   {
      Nombre:"Claudia",
      Apellido:"Bahamón",
      Icon:"/assets/icons/Famosos/C_Bahamon_Icon.png",
      Profesion:"Modelo, presentadora, influencer, ecologista.",
      Exp:"Vanart, Intibon, Desodorante Savital.",
      Texto:"Desde sus inicios Claudia llegó con toda la intención de poder sobresalir en los medios. Ha creado una marca tanto en lo personal como en lo profesional. Es una de las mejores presentadoras del país, que con su carisma y encanto ha llegado a ser imagen de marcas nacionales e internacionales. Claudia es embajadora y defensora de nuestro planeta.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/C_Bahamon01.png",
         "/assets/img/Famosos/C_Bahamon02.png",
      ]
   },
   {
      Nombre:"Catalina",
      Apellido:"Aristizábal",
      Icon:"/assets/icons/Famosos/C_Aristizabal_Icon.png",
      Profesion:"Modelo, presentadora, influencer.",
      Exp:"",
      Texto:"Desde su inicio la he acompañado en su desarrollo profesional como modelo, actriz, presentadora e influencer. Es una apasionada  por el ejercicio y la vida sana, donde es ejemplo de disciplina y constancia.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/C_Aristizabal01.png",
         "/assets/img/Famosos/C_Aristizabal02.png",
      ]
   },
   {
      Nombre:"Cristina",
      Apellido:"Hurtado",
      Icon:"/assets/icons/Famosos/C_Hurtado_Icon.png",
      Profesion:"Presentadora TV y radio, modelo, empresaria, influencer.",
      Exp:"Tuti fruti, Henkell Igora.",
      Texto:"Cristina ha sobresalido como modelo y presentadora desde sus inicios como participante de un reconocido reality donde  mostró desde el principio su interés por ser reconocida en el medio de la TV nacional.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/C_Hurtado01.png",
         "/assets/img/Famosos/C_Hurtado02.png",
      ]
   },
   {
      Nombre:"Carolina",
      Apellido:"Castro",
      Icon:"/assets/icons/Famosos/C_Castro_Icon.png",
      Profesion:"Empresaria, modelo, influencer.",
      Exp:"Tuti fruti, Henkell Igora.",
      Texto:"Carolina inició su carrera de modelaje a sus 14 años, desde entonces la he acompañado. Gracias a su empeño de sobresalir logró trabajar con los más reconocidos diseñadores internacionales y estar en las mejores pasarelas del mundo. Sobresale como una de las influencers de Colombia por su estilo y su pasión por la moda.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/C_Castro01.png",
         "/assets/img/Famosos/C_Castro02.png",
      ]
   },
   {
      Nombre:"Catalina",
      Apellido:"García Madameperine",
      Icon:"/assets/icons/Famosos/C_Madameperine_Icon.png",
      Profesion:"Cantante.",
      Exp:"",
      Texto:"Catalina es una joven cantante colombiana, reconocida por su grupo Monsieur Periné. Ella ha sobresalido rápidamente en Latinoamérica y Europa por su gran talento musical y estilo particular; además, por ser una embajadora de los temas ambientales.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/C_Madameperine01.png",
         "/assets/img/Famosos/C_Madameperine02.png",
      ]
   },
   {
      Nombre:"Erica",
      Apellido:"Ruini",
      Icon:"/assets/icons/Famosos/E_Ruini_Icon.png",
      Profesion:"Modelo.",
      Exp:"Punto Blanco, Johanna Ortiz, Kaanass Shoes, Spirito.",
      Texto:"Erica es una modelo colombo-italiana. Desde hace varios años reside en Colombia, donde ha sido imagen de grandes marcas. Su elegancia y belleza la han llevado a ser fotografiada por los mejores fotógrafos del país.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/E_Ruini01.png",
         "/assets/img/Famosos/E_Ruini02.png",
      ]
   },
   {
      Nombre:"Estefi",
      Apellido:"Borge",
      Icon:"/assets/icons/Famosos/E_Borge.png",
      Profesion:"Actriz, modelo, presentadora, escritora.",
      Exp:"",
      Texto:"Estefi comenzó su carrera como modelo, luego se enfocó en la actuación, y participó en el reality MasterChef Celebrity donde desarrolló la pasion por cocinar. Es creadora del libro best seller '¡Atrévete a cocinar!' Su enorme disciplina la ha llevado a destacarse como embajadora del mundo fitness.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/E_Borge01.png",
         "/assets/img/Famosos/E_Borge02.png",
      ]
   },
   {
      Nombre:"Fanny",
      Apellido:"Lu",
      Icon:"/assets/icons/Famosos/F_Lu_Icon.png",
      Profesion:"Cantante.",
      Exp:"",
      Texto:"Fanny Lu es una talentosa cantante, presentadora y animadora. Con un gran talento, su voz y su arrolladora personalidad, se ha consolidado como uno de los talentos colombianos más importantes. Con Fanny hemos trabajado en diferentes campañas publicitarias, en donde su personalidad es la atracción principal por su originalidad y su manera de crear versatilidad.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/F_Lu01.png",
         "/assets/img/Famosos/F_Lu02.png",
      ]
   },
   {
      Nombre:"Gabriela",
      Apellido:"Tafur",
      Icon:"/assets/icons/Famosos/G_Tafur_Icon.png",
      Profesion:"Modelo, influencer. ",
      Exp:"ARKITECT & DANIELLA BATLLE, BMW, W Radio, Yanbal.",
      Texto:"Gabriela sin duda es una de las más reconocidas ex reinas de Colombia, modelo y abogada de profesión. Se ha destacado por su carrera como modelo trabajando en las mejores pasarelas, ahora incursiona en el mundo de las comunicaciones mediante su participación como presentadora de la W Radio Colombia.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/G_Tafur01.png",
         "/assets/img/Famosos/G_Tafur02.png",
      ]
   },
   {
      Nombre:"Kathy",
      Apellido:"Sáenz",
      Icon:"/assets/icons/Famosos/K_Saenz_Icon.png",
      Profesion:"Actriz, modelo, influencer.",
      Exp:"Avon Fragancias, Chevrolet.",
      Texto:"Kathy ha sobresalido como emprendedora, modelo, actriz y empresaria. Enamorada de la vida, el amor y de la naturaleza. Ahora incursiona en su nuevo proyecto como diseñadora de joyas.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/K_Saenz01.png",
         "/assets/img/Famosos/K_Saenz02.png",
      ]
   },
   {
      Nombre:"Laura",
      Apellido:"Barjum",
      Icon:"/assets/icons/Famosos/L_Barjum.png",
      Profesion:"Artista, modelo, influencer.",
      Exp:"",
      Texto:"Laura, ex señorita Colombia, modelo, presentadora y actriz. Su personalidad la hace sobresalir en cualquier escenario acompañada de su buen humor y carisma. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/L_Barjum01.png",
         "/assets/img/Famosos/L_Barjum02.png",
      ]
   },
   {
      Nombre:"Laura",
      Apellido:"Londoño",
      Icon:"/assets/icons/Famosos/L_Londoño_Icon.png",
      Profesion:"Artista, modelo. ",
      Exp:"MNG Colombia, Metamucil.",
      Texto:"Desde que la conocí a sus trece años de edad, emprendimos muchos trabajos en el modelaje. Con su gran potencial y espontaneidad, ella fue abriendo espacio para la actuación. A su vez, con su perseverancia y carisma, ha logrado ser una de las actrices e influencers más activas y queridas en Colombia y Latinoamérica.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/L_Londono01.png",
         "/assets/img/Famosos/L_Londono02.png",
      ]
   },
   {
      Nombre:"Laura",
      Apellido:"Tobón",
      Icon:"/assets/icons/Famosos/L_Tobon_Icon.png",
      Profesion:"Modelo, Influencer.",
      Exp:"",
      Texto:"Laura es una de las modelos más activas del momento; desde su inicio se propuso sobresalir en el medio. Con su gran dominio frente a la cámara y el manejo de redes sociales es una de la influenciadoras más solicitadas en Colombia. Con su trabajo ha logrado internacionalizar su nombre en mercados tan importantes como el mexicano, y canales de televisión internacionales como E! Entertainment.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/L_Tobon01.png",
         "/assets/img/Famosos/L_Tobon02.png",
      ]
   },
   {
      Nombre:"María José",
      Apellido:"Barraza",
      Icon:"/assets/icons/Famosos/M_Barraza_Icon.png",
      Profesion:"Presentadora TV.",
      Exp:"",
      Texto:"María José fue reina de belleza, modelo y presentadora de TV. Trabaja en uno de los canales con mayor audiencia de Latinoamérica, Hola! TV. Se desempeña como  influencer de moda colombiana, gracias a su conocimiento y su pasión por la moda.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/M_Barraza01.png",
         "/assets/img/Famosos/M_Barraza02.png",
      ]
   },
   {
      Nombre:"María Lucía",
      Apellido:"Fernández",
      Icon:"/assets/icons/Famosos/.png",
      Profesion:"Presentadora TV",
      Exp:"",
      Texto:"María Lucía es una de las más reconocidas periodistas y presentadoras en Colombia, es una de las caras más reconocidas y de mayor credibilidad entre los presentadores de noticias. Comenzó como modelo y ha realizado una impecable carrera profesional en los medios de comunicación.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/M_Fernandez01.png",
         "/assets/img/Famosos/M_Fernandez02.png",
      ]
   },
   {
      Nombre:"Pilar",
      Apellido:"Schmitt",
      Icon:"/assets/icons/Famosos/P_Schmitt_Icon.png",
      Profesion:"Presentadora, modelo.",
      Exp:"",
      Texto:"Pilar es reconocida desde hace varios años como modelo y presentadpra de farándula de Noticias Caracol. Se caracteriza por su buen manejo ante la cámara, su carisma y profesionalismo.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/P_Schmitt01.png",
         "/assets/img/Famosos/P_Schmitt02.png",
      ]
   },
   {
      Nombre:"Toya",
      Apellido:"Montoya",
      Icon:"/assets/icons/Famosos/T_Montoya_Icon.png",
      Profesion:"Modelo, Influencer.",
      Exp:"Bronzini, Chocolyne.",
      Texto:"La Toya es una samaria que empezó su modelaje conmigo desde su juventud. Gracias a su sensibilidad social y medioambiental, es una abanderada de estos temas. Hemos trabajado en diversos proyectos en España y en México ahora radicada en Colombia nos muestra ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/T_Montoya01.png",
         "/assets/img/Famosos/T_Montoya02.png",
      ]
   },
   {
      Nombre:"Tatiana",
      Apellido:"Calderón",
      Icon:"/assets/icons/Famosos/T_Calderon_Icon.png",
      Profesion:"Deportista, piloto de automovilismo.",
      Exp:"",
      Texto:"A sus 27 años, Tatiana es corredora en la Fórmula 2 y se alista para llegar a la Fórmula Uno, siendo la primera mujer de nuestros tiempos en competir en esta categoría. Con su dedicación y profesionalismo muestra grandes resultados en su profesión. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/T_Calderon01.png",
         "/assets/img/Famosos/T_Calderon02.png",
      ]
   },
   {
      Nombre:"Yeimy Paola",
      Apellido:"Vargas",
      Icon:"/assets/icons/Famosos/Y_Vargas_Icon.png",
      Profesion:"Actriz y modelo.",
      Exp:"",
      Texto:"Yeimy es una mujer cartagenera que fue virreina nacional y luego se hizo modelo conmigo, de manera que la he acompañado desde el comienzo de su carrera. Incursionó en la actuación y ha participado en importantes telenovelas colombianas. Se  distingue por ser polifacética y muy versátil en sus actuaciones.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/Y_Vargas01.png",
         "/assets/img/Famosos/Y_Vargas02.png",
      ]
   },
   {
      Nombre:"Yaneth",
      Apellido:"Waldman",
      Icon:"/assets/icons/Famosos/Y_Waldman_Icon.png",
      Profesion:"Artista, presentadora, conferencista.",
      Exp:"Alimentos BARY.",
      Texto:"Con su impresionante personalidad y gran sonrisa, Yaneth conquista los corazones de su público. Con una gran tayectoria en la música  y actuación, se consolida como una celebridad. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/Y_Waldman01.png",
         "/assets/img/Famosos/Y_Waldman02.png",
      ]
   },
   {
      Nombre:"Carlitos",
      Apellido:"Vargas",
      Icon:"/assets/icons/Famosos/C_Vargas_Icon.png",
      Profesion:"Presentador.",
      Exp:"",
      Texto:"Carlos ha sobresalido como uno de los mejores presentadores de farándula del pais. Con su gran personalidad, humor, irreverencia y su gran honestidad, ha logrado poner su sello personal en cada uno de sus proyectos. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/C_Vargas01.png",
         "/assets/img/Famosos/C_Vargas02.png",
      ]
   },
   {
      Nombre:"Josse",
      Apellido:"Narváez",
      Icon:"/assets/icons/Famosos/J_Narvaez_Icon.png",
      Profesion:"Actor, cantante, presentador, modelo.",
      Exp:"",
      Texto:"Josse es un actor, cantante y presentador colombiano que comenzó como modelo conmigo. Cuenta con una buena trayectoria como actor y estamos planeando nuevos proyectos.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/J_Narvaez01.png",
         "/assets/img/Famosos/J_Narvaez02.png",
      ]
   },
   {
      Nombre:"Rafael",
      Apellido:"Novoa",
      Icon:"/assets/icons/Famosos/R_Novoa_Icon.png",
      Profesion:"Actor, Presentador, Modelo.",
      Exp:"",
      Texto:"Rafael empezó su carrera como modelo donde trabajamos e hicimos muchas campañas, luego trascendió como actor y ahora es reconocido no solo en Colombia sino a nivel internacional. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/R_Novoa01.png",
         "/assets/img/Famosos/R_Novoa02.png",
      ]
   },
   {
      Nombre:"Sebastián",
      Apellido:"Martínez",
      Icon:"/assets/icons/Famosos/S_Martinez_Icon.png",
      Profesion:"Actor, Presentador, Modelo.",
      Exp:"Fragancias Avon, Chevrolet, MNGcol.",
      Texto:"Con Sebastián tenemos una relación comercial de muchos años: juntos hemos participado exitosamente en grandes campañas publicitarias, logrando consolidar  su imagen como figura pública y como defensor de la vida saludable y del sano bienestar. Su gran sentido del humor y su ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/S_Martinez01.png",
         "/assets/img/Famosos/S_Martinez02.png",
      ]
   },
   {
      Nombre:"Mario Alberto",
      Apellido:"Yepes",
      Icon:"/assets/icons/Famosos/M_Yepes_Icon.png",
      Profesion:"Exfutbolista, excapitán de la Selección Colombia y entrenador de fútbol. ",
      Exp:"",
      Texto:"Al ser exjugador de la Selección Colombia, es un gran referente deportivo de nuestro país y reconocido tanto a nivel nacional como internacional. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/M_Yepes01.png",
         "/assets/img/Famosos/M_Yepes02.png",
      ]
   },
   {
      Nombre:"Falcao",
      Apellido:"",
      Icon:"/assets/icons/Famosos/Falcao_Icon.png",
      Profesion:"Deportista.",
      Exp:"",
      Texto:"Radamel Falcao es uno de los mejores jugadores del mundo, con el cual he podido compartir grandes campañas publicitarias colombianas. Es todo un referente deportivo y una figura pública  con gran carisma y profesionalismo. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/Falcao01.png",
         "/assets/img/Famosos/Falcao02.png",
      ]
   },
   {
      Nombre:"Santiago",
      Apellido:"Arias",
      Icon:"/assets/icons/Famosos/S_Arias_Icon.png",
      Profesion:"Deportista, Influencer.",
      Exp:"",
      Texto:"Santiago es futbolista de la Selección Colombia que actualmente juega en Europa, específicamente en el equipo Bayer 04 Liverkusen de la Bundesliga. Con su juventud y profesionalismo nos ha dejado un gran ejemplo de disciplina y compromiso.",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/S_Arias01.png",
         "/assets/img/Famosos/S_Arias02.png",
      ]
   },
   {
      Nombre:"Karim",
      Apellido:"Jiménez",
      Icon:"/assets/icons/Famosos/K_Jimenez_Icon.png",
      Profesion:"Modelo, Influencer.",
      Exp:"",
      Texto:"Karim una mujer apasionada por la moda y ha  sobresalido como influencer en los medios digitales. Ahora, como empresaria, nos muestra una nueva etapa donde su diseño y creatividad son sus mejores aliados. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/img/Famosos/K_Jimenez01.png",
         "/assets/img/Famosos/K_Jimenez02.png",
      ]
   },
   {
      Nombre:"Yuri Buenaventura",
      Icon:"/assets/icons/Famosos/Y_Buenaventura_Icon.png",
      Profesion:"Cantante",
      Exp:"",
      Texto:"Yuri, gran maestro y referente de la música  colombiana. Como compositor y cantante, con sus letras impregnadas de poesía y vivencias, y su voz inigualable, es conocido tanto a nivel nacional como internacional. ",
      Redes:[
         {
            insta:[
               {
                  Link:"www.instagram.com",
                  img:"/assets/icons/Insta_Pink.png",
               }
            ],
            face:[
               {
                  Link:"www.facebook.com",
                  img:"/assets/icons/Face_Pink.png",
               }
            ],
            Twitter:[
               {
                  Link:"www.twitter.com",
                  img:"/assets/icons/Twitter_Pink.png",
               }
            ]
         }
      ],
      Fotos:[
         "/assets/icons/Y_Buenaventura01.png",
         "/assets/icons/Y_Buenaventura02.png", 
      ]
   }
]